//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirwaysBusinessLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int PassID { get; set; }
        public string PassName { get; set; }
        public Nullable<int> PassAge { get; set; }
        public Nullable<int> BookingID { get; set; }
    }
}
